### ISSUE TITLE
Extended charset ?

### ISSUE THREAD

**Issue by sebastienroy** [Harbys/pico-ssd1306#3]
Hello,
Thank you for your simple but usefull driver. 
The available fonts, with a size from 5x8 to 16x32 are perfect for my usage.
However, the charset of these fonts are limited to the range 32 to 127 in the ascii table.

Would it be possible to get an extended charset (say 32 to 255 for instance) in order to include also characters such as é, ï ê, etc?
Or even better, a mechanism that allow to build our own font set ?

**Comment by Harbys** [comment]
You can create your own font set, it's actually briefly described in [TextRenderer readme](https://github.com/Harbys/pico-ssd1306/blob/master/textRenderer/readme.md).

If you want to support full printable ASCII range (32 - 255), you would have to build our own font with all the chars in the 32-255 range and delete 25th line from [textRenderer/TextRenderer.cpp](https://github.com/Harbys/pico-ssd1306/blob/master/textRenderer/TextRenderer.cpp)
```cpp
if(c < 32 || c > 126) return;
```

The decision not to include extended ascii characters was made in order to save space on the pico. I can add support for extended ascii, but I would do it over the weekend.

**Comment by sebastienroy** [comment]
Thank you very much for taking this extension into account.
I read the TextRenderer readme, but the explanation are a little bit short. In particular, you don't explain which tool to use to generate the font data. Also there is no indication on the origin of the "builtin" fonts...
Or maybe I didn't found it...

Concerning the memory usage, I've read that, on the RP2040, const variables are not copied in RAM but are kept in flash memory, which is 2Mb large. So I hope that the memory consumption of some extra characters would not be a problem.

**Comment by Harbys** [comment]
I implemented full ascii chars and made use of them optional. You can add
```c++
#define SSD1306_ASCII_FULL
```
to your project files to gain ability to use (32 - 255) ascii range
See [text_extended_ascii](https://github.com/Harbys/pico-ssd1306/tree/master/examples/text_extended_ascii) example to see how it works.

**Comment by sebastienroy** [comment]
Thank you very much for this update. I'm going to test it as soon as I can find enough time for that...
